In [36]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np
import os
from __future__ import absolute_import, division, print_function, unicode_literals

In [35]:

# Load the image
image_path = ''
image = Image.open(image_path)

# Convert the image to grayscale
gray_image = image.convert('L')

# Convert the grayscale image to a NumPy array
image_array = np.array(gray_image)

# Threshold the image to get a binary image
threshold = 128
binary_image = (image_array > threshold).astype(np.uint8)

# Display the binary image
print(binary_image)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 0 ... 0 1 1]
 ...
 [1 1 0 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [44]:
classes = ['bro', 'kro', 'par', 'pte', 'rex', 'ste', 'tri']

dataset = []

for c in classes:
    path = 'images/'+ c + '/' + c +'_'
    going = True
    count = 0
    while going:
        image_path = path + str(count) + '.jpeg'

        if not os.path.isfile(image_path):
            going = False 
            break
        
        image = Image.open(image_path)
        
        # Convert the image to grayscale
        gray_image = image.convert('L')

        # Convert the grayscale image to a NumPy array
        image_array = np.array(gray_image)

        # Threshold the image to get a binary image
        threshold = 128
        binary_image = (image_array > threshold).astype(np.uint8)

        dataset.append([binary_image, c])
        count += 1

        

In [45]:
dataset

[[array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 0, ..., 0, 1, 1],
         ...,
         [1, 1, 0, ..., 0, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
  'bro'],
 [array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 0, ..., 0, 1, 1],
         ...,
         [1, 1, 0, ..., 0, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
  'bro'],
 [array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 0, ..., 0, 1, 1],
         ...,
         [1, 1, 0, ..., 0, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
  'bro'],
 [array([[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 0, ..., 0, 1, 1],
         ...,
         [1, 1, 0, ..., 0, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
  'bro'],
 [array([[1, 1, 1, ..., 1, 1